---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      systemd:
        name: httpd
        state: restarted
        enabled: yes

    - name: install firewalld
      yum:
        name: firewalld
        state: latest
    - name: install telnet
      yum:
        name: telnet
        state: latest
    - name: add user bob
      user:
        name: bob
        state: present
        group: wheel
        uid: 2001
        generate_ssh_keys: yes
        

